name: build

on:
  pull_request:

jobs:
  lint_build_test:
    runs-on: ubuntu-20.04-16c-64g
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Sanity Check
        run: |
          cat /proc/cpuinfo

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          caller-workflow-name: test

      - name: Clippy check
        run: cargo clippy --all-features --all-targets --tests -- -D warnings

      - name: Run tests
        run: cargo test --all-features --locked
